blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/Flexget/Flexget/discussions
    about: Use GitHub discussions for message-board style questions and discussions
  - name: Report an issue with Web UI
    url: https://github.com/Flexget/webui/issues/new/choose
    about: Please report issues for our Web UI in the Flexget/webui repository
